// V1.14 — fair role-based performance: 55 core + 30 timing + 5 clean close + 10 extra bonus.
(function bootFairPerformanceV140(){
  if(typeof sb==='undefined'||typeof setView!=='function'||!profile){setTimeout(bootFairPerformanceV140,120);return;}
  if(window.__mindsFairPerformanceV140)return;window.__mindsFairPerformanceV140=true;
  let selectedDetailId=null;
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'');
  const num=v=>Number(v||0);
  const pct=v=>Math.round(num(v)*1000)/10;
  const monthName=v=>typeof prettyMonth==='function'?prettyMonth(v):String(v||'');
  const currentMonth=()=>typeof monthISO==='function'?monthISO():new Date().toISOString().slice(0,7)+'-01';
  const isAdminUser=()=>typeof isAdmin==='function'&&isAdmin();
  const roleLabels={tasarim:'Tasarım / Post',video:'Video Edit',sosyal_medya:'Sosyal Medya / Paylaşım'};
  function maxes(r){const m=r?.details?.score_max||{};return {core:num(m.core||55),timing:num(m.timing||30),close:num(m.close||5),extra:num(m.extra_bonus||10)};}
  function installStyles(){if(document.getElementById('performanceV140Style'))return;const s=document.createElement('style');s.id='performanceV140Style';s.textContent=`
    .perf140-rules{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px;margin:14px 0 16px}.perf140-rule{border:1px solid #293139;border-radius:13px;background:linear-gradient(145deg,#11181d,#0e1418);padding:14px}.perf140-rule small{display:block;color:#88949b;font-size:9px;text-transform:uppercase;letter-spacing:.06em}.perf140-rule b{display:block;font-size:20px;margin:6px 0 4px}.perf140-rule span{font-size:9px;color:#aab3b8;line-height:1.5}.perf140-top{display:grid;grid-template-columns:1.1fr 2fr;gap:14px;margin-bottom:16px}.perf140-leader,.perf140-status{border:1px solid #293139;border-radius:16px;background:#10161a;padding:18px}.perf140-leader{border-color:#7a6813;background:radial-gradient(circle at 10% 10%,rgba(220,203,42,.12),transparent 42%),linear-gradient(145deg,#17170d,#10161a)}.perf140-crown{width:42px;height:42px;border-radius:12px;display:grid;place-items:center;background:#2d2908;border:1px solid #665d11;font-size:21px;margin-bottom:12px}.perf140-leader h3{margin:0 0 5px;font-size:20px}.perf140-leader p,.perf140-status p{margin:0;color:#8d979d;font-size:10px;line-height:1.6}.perf140-leader strong{display:block;color:#e8df45;font-size:31px;margin-top:12px}.perf140-table tbody tr{cursor:pointer}.perf140-table tbody tr:hover{background:rgba(255,255,255,.025)}.perf140-score{font-size:18px;font-weight:900;color:#e1de39}.perf140-detail{margin-top:14px;border:1px solid #2b343a;border-radius:14px;background:#0e1418;padding:16px}.perf140-role-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px}.perf140-role{border:1px solid #252e34;border-radius:11px;padding:12px;background:#11171b}.perf140-role b{display:block;margin-bottom:7px}.perf140-role span{display:block;font-size:9px;color:#9aa4aa;margin:3px 0}.perf140-ok{color:#a8df78}.perf140-warn{color:#f0cf4d}.performance-award-badge-v140{position:absolute;right:-7px;bottom:-6px;width:26px;height:26px;border-radius:50%;display:grid;place-items:center;background:linear-gradient(145deg,#f2df43,#a98507);border:2px solid #11171b;box-shadow:0 3px 14px rgba(220,193,36,.4);font-size:13px;z-index:5;pointer-events:none}.profile-box #sideAvatar{position:relative}@media(max-width:1000px){.perf140-rules{grid-template-columns:repeat(2,1fr)}.perf140-top{grid-template-columns:1fr}.perf140-role-grid{grid-template-columns:1fr}}@media(max-width:600px){.perf140-rules{grid-template-columns:1fr}}
  `;document.head.appendChild(s);}
  function ensureAdminUI(){if(!isAdminUser())return;let nav=document.querySelector('.nav-item[data-view="performance"]');if(!nav){nav=document.createElement('button');nav.className='nav-item admin-nav';nav.dataset.view='performance';nav.innerHTML='★ <span>Performans</span>';const reports=document.querySelector('.nav-item[data-view="reports"]');(reports||document.querySelector('.sidebar nav'))?.insertAdjacentElement(reports?'afterend':'beforeend',nav);}let section=document.getElementById('performance');if(!section){section=document.createElement('section');section.id='performance';section.className='view';section.innerHTML='<div class="section-actions"><div><h2>Performans</h2><p>Otomatik puanlama; manuel müdahale yoktur.</p></div></div><div id="performanceBodyV113"></div>';const archive=document.getElementById('archive');archive?archive.insertAdjacentElement('beforebegin',section):document.querySelector('.main')?.appendChild(section);}nav.onclick=()=>{setView('performance');const t=document.getElementById('pageTitle'),s=document.getElementById('pageSub');if(t)t.textContent='Performans';if(s)s.textContent='Adil, rol bazlı otomatik performans ve Ayın Personeli.';refreshPerformanceV140(true);};}
  async function fetchScores(){const m=selectedMonth,cur=currentMonth();if(m<cur){const {data,error}=await sb.from('monthly_performance_scores').select('*').eq('month',m).order('rank',{ascending:true,nullsFirst:false});if(!error&&data?.length)return {rows:data.map(r=>({...r,full_name:(state.profiles||[]).find(p=>p.id===r.person_id)?.full_name||'Personel'})),finalized:true};}const {data,error}=await sb.rpc('performance_preview',{p_month:m});if(error)throw error;return {rows:data||[],finalized:false};}
  function roleHtml(details){const roles=details?.roles||{},keys=Object.keys(roles);if(!keys.length)return '<div class="empty">Bu ay puanlanabilir ana görev yok.</div>';return `<div class="perf140-role-grid">${keys.map(k=>{const r=roles[k]||{};return `<div class="perf140-role"><b>${esc(roleLabels[k]||k)}</b><span>Beklenen: ${num(r.expected)}</span><span>Tamamlanan: ${num(r.done)} · %${num(r.completion_pct).toFixed(1)}</span><span>Zaman puanı karşılığı: ${num(r.timing_units).toFixed(1)} · %${num(r.timing_pct).toFixed(1)}</span><span>Rol ağırlığı: %${Math.round(num(r.weight)*100)}</span></div>`;}).join('')}</div>`;}
  function render(rows,finalized){const body=document.getElementById('performanceBodyV113');if(!body)return;const ranked=rows.filter(r=>r.eligible&&r.rank!=null).sort((a,b)=>num(a.rank)-num(b.rank)),awardCandidates=ranked.filter(r=>r.details?.award_eligible===true||r.details?.award_eligible==='true'),leader=finalized?(awardCandidates[0]||null):(ranked[0]||null),isCurrent=selectedMonth===currentMonth(),onboarding=rows.some(r=>r.details?.onboarding_grace);let leaderNote='Ay kapanana kadar sıralama değişebilir.';if(leader){const ok=leader.details?.award_eligible===true||leader.details?.award_eligible==='true';leaderNote=finalized?(ok?'Ödül şartlarını sağlayan kazanan kesinleşti.':'Bu ay ödül şartlarını sağlayan personel yok.'):(ok?'Şu anda ödül adaylığı şartlarını da sağlıyor.':'Şu an lider ancak ödül için ana görev ≥ %90 ve toplam ≥ 80 gerekli.');}else if(finalized)leaderNote='Bu ay ödül şartlarını sağlayan personel yok.';
    body.innerHTML=`<div class="info-banner"><b>Yeni puan sistemi:</b> 55 Ana Görev + 30 Zamanlama + 5 Ayı Eksiksiz Kapatma + 10 Ekstra Katkı. Postlar ayın 1'inde tam zaman puanı alır; her gecikme günü %10 düşer ve 11. günden sonra post zaman puanı 0 olur. Videolar ay sonuna kadar hazır olmalıdır. Aslı yalnızca zamanında hazırlanmış içeriklerin paylaşımından sorumludur.${onboarding?' <b>Ağustos 2026 eğitim/test ayıdır; resmi ödül üretilmez.</b>':''}</div>
    <div class="perf140-rules"><div class="perf140-rule"><small>Ana Görev</small><b>55 Puan</b><span>Kişinin yalnızca kendi gerçek rolü: Umut %60 video/%40 tasarım, Yusuf video, Aslı %40 tasarım/%60 paylaşım, İmran tasarım.</span></div><div class="perf140-rule"><small>Zamanlama</small><b>30 Puan</b><span>Post: 1. gün %100, her gün -%10. Video: ay sonuna kadar. Paylaşım: hazır içerikler ay bitmeden.</span></div><div class="perf140-rule"><small>Temiz Kapanış</small><b>5 Puan</b><span>Kendi ana sorumluluklarının tamamını ay sonunda eksiksiz kapatana verilir.</span></div><div class="perf140-rule"><small>Ekstra Katkı</small><b>+10 Puan</b><span>Ekstra işler ve gerçek çekimler bonus. Çekim yapılmayan ay kimseye eksi yazılmaz.</span></div></div>
    <div class="perf140-top"><div class="perf140-leader"><div class="perf140-crown">🏆</div><p>${finalized?'Ayın Personeli':isCurrent?'Şu An Lider':'Hesaplanan Lider'} · ${monthName(selectedMonth)}</p><h3>${leader?esc(leader.full_name):'Henüz sonuç yok'}</h3><strong>${leader?num(leader.total_score).toFixed(1):'—'}</strong><p>${leaderNote}</p></div><div class="perf140-status"><h4>${monthName(selectedMonth)} Puan Durumu</h4><p>Ödül adaylığı için <b>ana görev tamamlama en az %90</b> ve <b>toplam puan en az 80</b> olmalıdır. Ekstra işler ana görev eksikliğini kapatamaz. Eşit toplam puanda sırasıyla ana görev tamamlama, zamanlama ve ekstra katkı dikkate alınır.</p></div></div>
    <div class="panel"><div class="table-wrap"><table class="perf140-table"><thead><tr><th>Sıra</th><th>Personel</th><th>Ana Görev</th><th>Zamanlama</th><th>Temiz Kapanış</th><th>Ekstra Bonus</th><th>Toplam</th></tr></thead><tbody>${rows.map(r=>{const mx=maxes(r),close=num(r.details?.close_score),award=r.details?.award_eligible===true||r.details?.award_eligible==='true';return `<tr data-perf140-person="${r.person_id}"><td><b>${r.rank?('#'+r.rank):'—'}</b></td><td><b>${esc(r.full_name)}</b><div class="${award?'perf140-ok':'perf140-warn'}">${award?'Ödül adayı':'Şartlar henüz tamam değil'}</div></td><td>${num(r.core_score).toFixed(1)} / ${mx.core}</td><td>${num(r.timing_score).toFixed(1)} / ${mx.timing}</td><td>${close.toFixed(1)} / ${mx.close}</td><td>${num(r.extra_score).toFixed(1)} / +${mx.extra}</td><td><span class="perf140-score">${num(r.total_score).toFixed(1)}</span></td></tr>`;}).join('')||'<tr><td colspan="7" class="empty">Puan bulunamadı.</td></tr>'}</tbody></table></div></div><div id="performanceDetailV140"></div>`;
    body.querySelectorAll('[data-perf140-person]').forEach(tr=>tr.onclick=()=>{selectedDetailId=tr.dataset.perf140Person;const r=rows.find(x=>x.person_id===selectedDetailId),d=document.getElementById('performanceDetailV140');if(!r||!d)return;const mx=maxes(r),award=r.details?.award_eligible===true||r.details?.award_eligible==='true';d.innerHTML=`<div class="perf140-detail"><h4>${esc(r.full_name)} · Puan Detayı</h4><p class="muted">${esc(r.details?.responsibility_summary||'Rol bazlı görev profili')}</p>${roleHtml(r.details)}<div class="perf140-role-grid" style="margin-top:10px"><div class="perf140-role"><b>Ana Görev</b><span>${num(r.core_score).toFixed(1)} / ${mx.core}</span><span>Tamamlama: %${pct(r.details?.completion_ratio).toFixed(1)}</span></div><div class="perf140-role"><b>Zamanlama</b><span>${num(r.timing_score).toFixed(1)} / ${mx.timing}</span><span>Zamanlama oranı: %${pct(r.details?.timing_ratio).toFixed(1)}</span></div><div class="perf140-role"><b>Temiz Kapanış</b><span>${num(r.details?.close_score).toFixed(1)} / ${mx.close}</span><span>Tüm ana görevler %100 tamamlanırsa verilir.</span></div><div class="perf140-role"><b>Ekstra Katkı</b><span>Ağırlıklı katkı: ${num(r.details?.weighted_extra_units).toFixed(1)} birim</span><span>Ekstra kayıt: ${num(r.details?.extra_quantity)} · Çekim: ${num(r.details?.shoot_count)}</span><span>Bonus: ${num(r.extra_score).toFixed(1)} / +${mx.extra}</span></div><div class="perf140-role"><b>Ödül Uygunluğu</b><span class="${award?'perf140-ok':'perf140-warn'}">${award?'✓ Şartları sağlıyor':'Ana görev ≥ %90 ve toplam ≥ 80 gerekli'}</span></div></div></div>`;};
  }
  async function refreshPerformanceV140(showError=false){if(!isAdminUser())return;try{const {rows,finalized}=await fetchScores();render(rows,finalized);}catch(e){console.error('V1.14 performance',e);if(showError&&typeof toast==='function')toast('Performans yüklenemedi: '+(e?.message||e),true);}}
  async function refreshAwardBadge(){try{const display=currentMonth();const {data,error}=await sb.from('employee_month_awards').select('score,performance_month,display_month').eq('person_id',profile.id).eq('display_month',display).maybeSingle();if(error)return;const av=document.getElementById('sideAvatar');if(!av)return;av.querySelector('.performance-award-badge-v140')?.remove();if(data){const b=document.createElement('span');b.className='performance-award-badge-v140';b.textContent='🏆';b.title=`Ayın Personeli · ${monthName(data.performance_month)} · ${num(data.score).toFixed(1)} puan`;av.appendChild(b);}}catch(e){console.warn('Award badge',e);}}
  installStyles();ensureAdminUI();refreshAwardBadge();document.addEventListener('change',e=>{if(e.target?.id==='monthPicker'&&document.getElementById('performance')?.classList.contains('active-view'))setTimeout(()=>refreshPerformanceV140(false),80);});setInterval(()=>{if(isAdminUser()&&document.getElementById('performance')?.classList.contains('active-view'))refreshPerformanceV140(false);},60000);window.refreshPerformanceV140=refreshPerformanceV140;
})();