// V1.14 — extras support registered/external clients and weighted work types for performance.
(function bootExtraWorkTypesV140(){
  if(typeof openModal!=='function'||typeof sb==='undefined'||typeof state==='undefined'||typeof renderAll!=='function'){setTimeout(bootExtraWorkTypesV140,120);return;}
  if(window.__mindsExtraWorkTypesV140)return; window.__mindsExtraWorkTypesV140=true;
  const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??'');
  const canManage=x=>typeof canManageExtra==='function'?canManageExtra(x):(isAdmin()||(x?.person_id===profile?.id&&x?.created_by===profile?.id));
  const typeMeta={adaptasyon:['Ekstra Post / Adaptasyon','×1'],video_edit:['Video Edit','×1,5'],cekim:['Çekim / Prodüksiyon','×1,5'],logo_kurumsal:['Logo / Kurumsal Kimlik','×2'],katalog_brosur:['Katalog / Broşür','×2'],acik_hava_matbaa:['Açık Hava / Matbaa','×1,5'],diger:['Diğer','×1']};
  const typeLabel=v=>(typeMeta[v]||typeMeta.diger)[0], typeWeight=v=>(typeMeta[v]||typeMeta.diger)[1];
  function clientLabel(x){if(x.kind==='ajans')return '<span class="badge blue">Ajans İçi</span>';if(x.firm_id){const f=typeof firm==='function'?firm(x.firm_id):(state.firms||[]).find(v=>v.id===x.firm_id);return `<b>${esc(f?.name||'Kayıtlı Firma')}</b><div class="muted">Kayıtlı firma</div>`;}if(x.external_client_name)return `<b>${esc(x.external_client_name)}</b><div class="muted"><span class="badge yellow">Harici</span> Tek seferlik müşteri / kişi</div>`;return '—';}
  function renderExtrasV140(){const rows=typeof monthExtras==='function'?monthExtras():(state.extras||[]).filter(x=>x.month===selectedMonth),tbody=document.getElementById('extraRows');if(!tbody)return;tbody.innerHTML=rows.map(x=>`<tr><td>${x.kind==='firma'?'Müşteri':'Ajans'}</td><td>${x.source==='staff'?'Personel':'Yönetici'}</td><td>${clientLabel(x)}</td><td><b>${esc(x.title)}</b><div class="muted"><span class="badge blue">${esc(typeLabel(x.extra_work_type))}</span> ${esc(typeWeight(x.extra_work_type))} katkı</div></td><td>${Number(x.quantity||0)}</td><td>${esc(typeof personName==='function'?personName(x.person_id):'—')}</td><td>${typeof formatDate==='function'?formatDate(x.work_date):esc(x.work_date)}</td><td>${typeof actionButtons==='function'?actionButtons('extra',x.id,canManage(x)):(canManage(x)?`<button class="small-primary" data-edit-extra="${x.id}">Güncelle</button>`:'—')}</td></tr>`).join('')||'<tr><td colspan="8" class="empty">Bu ay ekstra iş yok.</td></tr>';}
  function openExtraModalV140(x=null){
    if(x&&!canManage(x))return toast('Bu ekstra işi düzenleme yetkin yok.',true);
    const available=typeof activeFirms==='function'?activeFirms():(state.firms||[]).filter(f=>f.active),mode=x?.kind==='ajans'?'agency':x?.external_client_name?'external':'registered',selectedPerson=x?.person_id||profile.id,selectedType=x?.extra_work_type||'diger';
    openModal(x?'Ekstra İşi Güncelle':'Ekstra İş Ekle',`<div class="form-grid">
      <div class="field full"><label>İş Kimin İçin?</label><select name="target_mode" id="extraTargetModeV140"><option value="registered" ${mode==='registered'?'selected':''}>Kayıtlı Firma</option><option value="external" ${mode==='external'?'selected':''}>Harici Müşteri / Kişi</option><option value="agency" ${mode==='agency'?'selected':''}>Ajans İçi</option></select><div class="field-help">Harici müşteri Firmalar listesine eklenmez.</div></div>
      <div class="field full" id="extraRegisteredFirmV140"><label>Kayıtlı Firma</label><select name="firm"><option value="">Seç</option>${available.map(f=>`<option value="${f.id}" ${x?.firm_id===f.id?'selected':''}>${esc(f.name)}</option>`).join('')}</select></div>
      <div class="field full" id="extraExternalClientV140"><label>Harici Müşteri / Kişi Adı</label><input name="external_client" maxlength="120" placeholder="Örn. Ahmet Yılmaz / ABC Marka" value="${esc(x?.external_client_name||'')}"></div>
      ${isAdmin()?`<div class="field full"><label>İşi Yapan Personel</label><select name="person">${activeProfiles().map(p=>`<option value="${p.id}" ${p.id===selectedPerson?'selected':''}>${esc(p.full_name)}</option>`).join('')}</select></div>`:`<input type="hidden" name="person" value="${profile.id}">`}
      <div class="field full"><label>Ekstra İş Türü</label><select name="extra_type">${Object.entries(typeMeta).map(([k,v])=>`<option value="${k}" ${k===selectedType?'selected':''}>${esc(v[0])} · ${esc(v[1])}</option>`).join('')}</select><div class="field-help">Tür, performanstaki ekstra katkı ağırlığını otomatik belirler.</div></div>
      <div class="field full"><label>Yapılan İş</label><input name="title" required placeholder="Örn. Reels edit / logo tasarımı" value="${esc(x?.title||'')}"></div>
      <div class="field"><label>Adet</label><input name="qty" type="number" min="1" step="1" required value="${x?.quantity??1}"></div><div class="field"><label>Tarih</label><input name="date" type="date" required value="${x?.work_date||(typeof defaultDateForSelectedMonth==='function'?defaultDateForSelectedMonth():new Date().toISOString().slice(0,10))}"></div>
      <div class="field full"><label>Not</label><textarea name="notes">${esc(x?.notes||'')}</textarea></div><div class="form-actions field full"><button type="button" class="ghost" onclick="closeModal()">Vazgeç</button><button class="primary" type="submit">Kaydet</button></div></div>`,async fd=>{
        const targetMode=String(fd.get('target_mode')||'registered'),fid=String(fd.get('firm')||'').trim()||null,external=String(fd.get('external_client')||'').trim(),extraType=String(fd.get('extra_type')||'diger');
        if(targetMode==='registered'&&!fid)throw new Error('Kayıtlı firma seçmelisin.');if(targetMode==='external'&&external.length<2)throw new Error('Harici müşteri / kişi adını yazmalısın.');if(!typeMeta[extraType])throw new Error('Ekstra iş türü geçersiz.');if(typeof assertSelectedMonthDate==='function')assertSelectedMonthDate(fd.get('date'),'Ekstra iş tarihi');const q=Number(fd.get('qty'));if(!Number.isInteger(q)||q<1)throw new Error('Ekstra iş adedi en az 1 olmalı.');const targetPerson=isAdmin()?(fd.get('person')||profile.id):profile.id;
        const payload={month:selectedMonth,kind:targetMode==='agency'?'ajans':'firma',firm_id:targetMode==='registered'?fid:null,external_client_name:targetMode==='external'?external:null,extra_work_type:extraType,title:String(fd.get('title')||'').trim(),quantity:q,person_id:targetPerson,work_date:fd.get('date'),notes:String(fd.get('notes')||'').trim()||null};
        if(x){const {error}=await sb.from('extra_works').update(payload).eq('id',x.id);if(error)throw error;}else{payload.source=isAdmin()?'admin':'staff';payload.created_by=profile.id;const {error}=await sb.from('extra_works').insert(payload);if(error)throw error;}
    });
    setTimeout(()=>{const modeSel=document.getElementById('extraTargetModeV140'),reg=document.getElementById('extraRegisteredFirmV140'),ext=document.getElementById('extraExternalClientV140');const sync=()=>{const v=modeSel?.value||'registered';if(reg)reg.style.display=v==='registered'?'':'none';if(ext)ext.style.display=v==='external'?'':'none';};modeSel?.addEventListener('change',sync);sync();},0);
  }
  openExtraModal=openExtraModalV140;renderExtras=renderExtrasV140;window.openExtraModal=openExtraModalV140;try{renderExtrasV140();}catch(e){console.warn('Extra work types initial render',e);}
})();