function openWorkModal(w=null){ const fm=w?state.months.find(m=>m.id===w.firm_month_id):null; let available=activeFirms().filter(f=>!!currentFirmMonth(f.id)); if(w&&fm){ const oldFirm=firm(fm.firm_id); if(oldFirm&&!available.some(f=>f.id===oldFirm.id)) available=[oldFirm,...available]; } if(!available.length) return toast('Önce firma ve aylık paket oluşturulmalı.',true); openModal(w?'İşi Güncelle':'Yeni Paket İşi',`<div class="form-grid"><div class="field full"><label>Firma</label><select name="firm" required ${w?'disabled':''}>${available.map(f=>`<option value="${f.id}" ${(fm?.firm_id===f.id)?'selected':''}>${escapeHtml(f.name)}</option>`).join('')}</select></div><div class="field full"><label>İş Başlığı</label><input name="title" required value="${escapeHtml(w?.title||'')}"></div><div class="field"><label>Tür</label><select name="type"><option value="post" ${w?.type==='post'?'selected':''}>Post</option><option value="video" ${w?.type==='video'?'selected':''}>Video</option></select></div>${isAdmin()?`<div class="field"><label>Sorumlu</label><select name="person"><option value="">Seçilmedi</option>${peopleOptions(w?.assigned_to||profile.id)}</select></div>`:`<div class="field"><label>Sorumlu</label><input value="${escapeHtml(profile.full_name)}" disabled><input type="hidden" name="person" value="${profile.id}"></div>`}<div class="field"><label>Hazırlık</label><select name="status">${['bekliyor','devam_ediyor','hazir','revizede','onaylandi'].map(x=>`<option value="${x}" ${w?.status===x?'selected':''}>${workStatusLabel(x)}</option>`).join('')}</select></div><div class="field"><label>Paylaşım</label><select name="share">${['paylasilmadi','planlandi','paylasildi'].map(x=>`<option value="${x}" ${w?.share_status===x?'selected':''}>${shareLabel(x)}</option>`).join('')}</select></div><div class="field"><label>Tarih</label><input type="date" name="date" value="${w?.work_date||defaultDateForSelectedMonth()}"></div><div class="field full"><label>Not</label><textarea name="notes">${escapeHtml(w?.notes||'')}</textarea></div><div class="form-actions field full"><button type="button" class="ghost" onclick="closeModal()">Vazgeç</button><button class="primary">Kaydet</button></div></div>`,async fd=>{ const fid=w?fm.firm_id:fd.get('firm'), month=currentFirmMonth(fid); if(!month) throw new Error('Bu firma için seçili ay paketi yok.'); assertSelectedMonthDate(fd.get('date'),'İş tarihi'); const share=fd.get('share'); const payload={title:fd.get('title'),type:fd.get('type'),status:fd.get('status'),share_status:share,assigned_to:fd.get('person')||null,work_date:fd.get('date'),shared_date:share==='paylasildi'?(w?.shared_date||fd.get('date')):null,notes:fd.get('notes')}; if(w){ const {error}=await sb.from('works').update(payload).eq('id',w.id); if(error) throw error; } else { payload.firm_month_id=month.id; payload.created_by=profile.id; const {error}=await sb.from('works').insert(payload); if(error) throw error; } }); }

function openExtraModal(){
  openModal('Ekstra İş Ekle',`<div class="form-grid"><div class="field"><label>Tür</label><select name="kind" id="extraKind"><option value="firma">Firma İçin Ekstra</option><option value="ajans">Ajans İçi Ekstra</option></select></div><div class="field"><label>Firma</label><select name="firm" id="extraFirm"><option value="">Seç</option>${firmOptions()}</select></div>${isAdmin()?`<div class="field full"><label>İşi Yapan Personel</label><select name="person"><option value="${profile.id}">${escapeHtml(profile.full_name)}</option>${activeProfiles().filter(p=>p.id!==profile.id).map(p=>`<option value="${p.id}">${escapeHtml(p.full_name)}</option>`).join('')}</select></div>`:''}<div class="field full"><label>Yapılan İş</label><input name="title" required></div><div class="field"><label>Adet</label><input name="qty" type="number" min="1" required value="1"></div><div class="field"><label>Tarih</label><input name="date" type="date" required value="${defaultDateForSelectedMonth()}"></div><div class="field full"><label>Not</label><textarea name="notes"></textarea></div><div class="form-actions field full"><button type="button" class="ghost" onclick="closeModal()">Vazgeç</button><button class="primary" type="submit">Kaydet</button></div></div>`,async fd=>{
    const kind=fd.get('kind'), fid=fd.get('firm')||null; if(kind==='firma'&&!fid) throw new Error('Firma seçmelisin.'); assertSelectedMonthDate(fd.get('date'),'Ekstra iş tarihi');
    const qty=Number(fd.get('qty')); if(!Number.isInteger(qty)||qty<1) throw new Error('Ekstra iş adedi en az 1 olmalı.');
    const targetPerson=isAdmin()?(fd.get('person')||profile.id):profile.id;
    const payload={month:selectedMonth,kind,source:isAdmin()?'admin':'staff',firm_id:kind==='firma'?fid:null,title:String(fd.get('title')||'').trim(),quantity:qty,person_id:targetPerson,work_date:fd.get('date'),notes:String(fd.get('notes')||'').trim()||null,created_by:profile.id};
    const {error}=await sb.from('extra_works').insert(payload); if(error) throw error;
  });
}

function openShootModal(shoot=null){
  let available=activeFirms(); if(shoot){ const oldFirm=firm(shoot.firm_id); if(oldFirm&&!available.some(f=>f.id===oldFirm.id)) available=[oldFirm,...available]; } if(!available.length) return toast('Önce firma eklemelisin.',true);
  openModal(shoot?'Çekimi Güncelle':'Yeni Çekim',`<div class="form-grid"><div class="field full"><label>Firma</label><select name="firm" required>${available.map(f=>`<option value="${f.id}" ${shoot?.firm_id===f.id?'selected':''}>${escapeHtml(f.name)}</option>`).join('')}</select></div><div class="field full"><label>Çekim Başlığı</label><input name="title" placeholder="Örn. Aylık sosyal medya çekimi" value="${escapeHtml(shoot?.title||'')}"></div><div class="field"><label>Çekim Tarihi</label><input name="date" type="date" required value="${shoot?.shoot_date||defaultDateForSelectedMonth()}"></div><div class="field"><label>Çekilen Video İçeriği</label><input name="video_count" type="number" min="1" required value="${shoot?.video_count??1}"></div>${isAdmin()?`<div class="field full"><label>Sorumlu Personel</label><select name="person"><option value="">Seçilmedi</option>${peopleOptions(shoot?.responsible_id||profile.id)}</select></div>`:`<div class="field full"><label>Sorumlu Personel</label><input value="${escapeHtml(profile.full_name)}" disabled><input type="hidden" name="person" value="${profile.id}"></div>`}<div class="field full"><label>Not</label><textarea name="notes" placeholder="Çekim detayı, lokasyon, içerik notu...">${escapeHtml(shoot?.notes||'')}</textarea></div><div class="form-actions field full"><button type="button" class="ghost" onclick="closeModal()">Vazgeç</button><button class="primary" type="submit">Kaydet</button></div></div>`,async fd=>{
    assertSelectedMonthDate(fd.get('date'),'Çekim tarihi'); const count=Number(fd.get('video_count')); if(!Number.isInteger(count)||count<1) throw new Error('Çekilen video içeriği en az 1 olmalı.');
    const payload={firm_id:fd.get('firm'),shoot_date:fd.get('date'),title:String(fd.get('title')||'').trim()||null,video_count:count,responsible_id:fd.get('person')||null,notes:String(fd.get('notes')||'').trim()||null};
    if(shoot){ const {error}=await sb.from('shoots').update(payload).eq('id',shoot.id); if(error) throw error; }
    else { payload.created_by=profile.id; const {error}=await sb.from('shoots').insert(payload); if(error) throw error; }
  });
}

function openPersonModal(){ if(!isAdmin()) return toast('Bu işlem yalnızca yönetici hesabında kullanılabilir.',true); openModal('Personel Ekle',`<div class="form-grid"><div class="field full"><label>Ad Soyad</label><input name="name" required></div><div class="field"><label>Görev / Rol</label><input name="title" placeholder="Grafik Tasarım, Video Editör..."></div><div class="field"><label>Kullanıcı Adı</label><input name="username" required></div><div class="field full"><label>Geçici Şifre</label><input name="password" type="password" required minlength="8"><div class="field-help">En az 8 karakter.</div></div><div class="form-actions field full"><button type="button" class="ghost" onclick="closeModal()">Vazgeç</button><button class="primary">Hesap Oluştur</button></div></div>`,async fd=>{ const {data:{session:s}}=await sb.auth.getSession(); const r=await fetch(`${SUPABASE_URL}/functions/v1/manage-users`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':`Bearer ${s.access_token}`},body:JSON.stringify({action:'create',full_name:fd.get('name'),job_title:fd.get('title'),username:fd.get('username'),password:fd.get('password')})}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'Personel oluşturulamadı.'); }); }

async function manageUser(body){ const {data:{session:s}}=await sb.auth.getSession(); const r=await fetch(`${SUPABASE_URL}/functions/v1/manage-users`,{method:'POST',headers:{'Content-Type':'application/json','apikey':SUPABASE_KEY,'Authorization':`Bearer ${s.access_token}`},body:JSON.stringify(body)}); const j=await r.json(); if(!r.ok) throw new Error(j.error||'İşlem başarısız.'); }
