// V1.14 — monthly "shoot not planned" note. Informational only; shooting is bonus, never a required performance target.
(function bootShootNotesV140(){
  if(typeof sb==='undefined'||typeof state==='undefined'||typeof renderAll!=='function'){setTimeout(bootShootNotesV140,120);return;}
  if(window.__mindsShootNotesV140)return;window.__mindsShootNotesV140=true;
  let notes=[],firms=[];const esc=v=>typeof escapeHtml==='function'?escapeHtml(String(v??'')):String(v??''),nameOf=id=>(state.profiles||[]).find(p=>p.id===id)?.full_name||'Personel',currentMonth=()=>typeof monthISO==='function'?monthISO():new Date().toISOString().slice(0,7)+'-01';
  async function loadFirms(){const {data,error}=await sb.rpc('list_shoot_firms_for_team');if(!error)firms=data||[];}
  const firmName=id=>firms.find(f=>f.id===id)?.name||(state.firms||[]).find(f=>f.id===id)?.name||'Firma';
  function ensureUI(){const section=document.getElementById('shoots'),actions=section?.querySelector('.section-actions');if(!section)return null;let btn=document.getElementById('addShootExemptionBtnV139');if(!btn&&actions){btn=document.createElement('button');btn.id='addShootExemptionBtnV139';btn.className='ghost';btn.textContent='+ Çekim Yapılmadı';btn.style.marginLeft='8px';document.getElementById('addShootBtn')?.insertAdjacentElement('afterend',btn);btn.onclick=openModalNote;}if(btn)btn.style.display=selectedMonth===currentMonth()?'':'none';let panel=document.getElementById('shootExemptionPanelV139');if(!panel){panel=document.createElement('div');panel.id='shootExemptionPanelV139';panel.className='panel';panel.style.marginBottom='12px';(document.getElementById('sharedShootsInfoV124')||actions)?.insertAdjacentElement('afterend',panel);}return panel;}
  async function refresh(){await loadFirms();const panel=ensureUI();if(!panel)return;const {data,error}=await sb.from('shoot_exemptions').select('*').eq('month',selectedMonth).order('created_at',{ascending:true});if(error)return console.warn('shoot notes',error);notes=data||[];panel.innerHTML=`<div class="panel-head"><div><h3>Bu Ay Çekim Yapılmayan Firmalar</h3><p>Operasyonel bilgi içindir. Yeni performans sisteminde çekim zorunlu hedef değildir; yapılan çekimler yalnızca ekstra bonus katkısı sağlar.</p></div><span class="badge ${notes.length?'yellow':'green'}">${notes.length?`${notes.length} kayıt`:'Kayıt yok'}</span></div>${notes.length?`<div class="table-wrap"><table><thead><tr><th>Firma</th><th>Sorumlu</th><th>Durum</th><th>Not</th><th>İşlem</th></tr></thead><tbody>${notes.map(x=>`<tr><td><b>${esc(firmName(x.firm_id))}</b></td><td>${esc(nameOf(x.responsible_id))}</td><td><span class="badge yellow">Bu Ay Çekim Yapılmadı</span></td><td>${esc(x.reason||'—')}</td><td>${isAdmin()||x.responsible_id===profile.id||x.created_by===profile.id?`<button class="small-danger" data-delete-shoot-note="${x.id}">Kaldır</button>`:'—'}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty compact-empty">Bu ay için “çekim yapılmadı” kaydı yok.</div>'}`;}
  async function openModalNote(){if(selectedMonth!==currentMonth())return toast('Bu kayıt yalnızca güncel ay için girilebilir.',true);await loadFirms();const active=firms.filter(f=>f.active!==false),personField=isAdmin()?`<div class="field full"><label>İlgili Personel</label><select name="person" required>${(state.profiles||[]).filter(p=>p.active&&p.role==='staff').map(p=>`<option value="${p.id}">${esc(p.full_name)}</option>`).join('')}</select></div>`:`<input type="hidden" name="person" value="${profile.id}">`;openModal('Bu Ay Çekim Yapılmadı',`<div class="form-grid"><div class="field full"><label>Firma</label><select name="firm" required>${active.map(f=>`<option value="${f.id}">${esc(f.name)}</option>`).join('')}</select></div>${personField}<div class="field full"><label>Neden / Not</label><textarea name="reason" placeholder="Örn. Firma bu ay çekim istemedi"></textarea><div class="field-help">Bu kayıt yalnızca bilgi amaçlıdır; performansta eksi puan oluşturmaz.</div></div><div class="form-actions field full"><button type="button" class="ghost" onclick="closeModal()">Vazgeç</button><button class="primary" type="submit">Kaydet</button></div></div>`,async fd=>{const payload={month:selectedMonth,firm_id:fd.get('firm'),responsible_id:isAdmin()?fd.get('person'):profile.id,reason:String(fd.get('reason')||'').trim()||null,created_by:profile.id};const {error}=await sb.from('shoot_exemptions').upsert(payload,{onConflict:'month,firm_id,responsible_id'});if(error)throw error;setTimeout(refresh,80);});}
  document.addEventListener('click',async e=>{const b=e.target.closest('[data-delete-shoot-note]');if(!b)return;if(!confirm('“Bu ay çekim yapılmadı” kaydı kaldırılsın mı?'))return;const {error}=await sb.from('shoot_exemptions').delete().eq('id',b.dataset.deleteShootNote);if(error)return toast(error.message,true);await refresh();});
  document.addEventListener('change',e=>{if(e.target?.id==='monthPicker')setTimeout(refresh,120);});const prev=renderAll;renderAll=function(){prev();setTimeout(refresh,60);};setTimeout(refresh,350);
})();